title: Josh's Portfolio
description: Full-stack developer and creator.
theme: minima 
baseurl: "/portfolio"
url: "https://kartu-pro.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:path/
