title: Josh's Portfolio
tagline: Full-stack developer, creator, linguaphile.
bio: I’m a developer driven by the structural parallels between human syntax and source code, exploring how technology can bridge the gap between global tongues.
theme: minima 
baseurl: "/portfolio"
url: "https://kartu-pro.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:path/
